# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM python:3.10-alpine

# Install system dependencies (if any)
RUN apk add --no-cache build-base \
    && apk add --no-cache libffi-dev openssl-dev

# Set working directory
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Upgrade pip
RUN pip install --upgrade pip

# Install dependencies
RUN pip install --no-cache-dir fastmcp requests python-dotenv

# Run the MCP server
CMD ["python", "pubmed_search_mcp_server.py"]
